### ISSUE TITLE
Unable to `pip install pyvo` under Python 3.9

### ISSUE THREAD

**Issue by barentsen** [astropy/pyvo#250]
I seem unable to `pip install pyvo==1.1` under Python 3.9.1 (it does work under Python 3.8.6).  The most recent version of pyvo that seems to install under Python 3.9 for me is pyvo 0.6.

Steps to reproduce:
```bash
$ pyenv virtualenv 3.9.1 pyvo
$ pyenv shell pyvo
$ python -m pip install pip --upgrade
$ python --version
Python 3.9.1
$ pip --version
pip 21.0.1 from /Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/pip (python 3.9)
$ pip install pyvo==1.1
Collecting pyvo==1.1
  Using cached pyvo-1.1.tar.gz (804 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/gb/.pyenv/versions/pyvo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/setup.py'"'"'; __file__='"'"'/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-pip-egg-info-5aj77r0u
         cwd: /private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/
    Complete output (59 lines):
      ERROR: Command errored out with exit status 1:
       command: /Users/gb/.pyenv/versions/pyvo/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-wheel-_aiy07oc/astropy-helpers_5a893df2546744ba8a79882b707655cd/setup.py'"'"'; __file__='"'"'/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-wheel-_aiy07oc/astropy-helpers_5a893df2546744ba8a79882b707655cd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-wheel-dyu4ynd0
           cwd: /private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-wheel-_aiy07oc/astropy-helpers_5a893df2546744ba8a79882b707655cd/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for astropy-helpers
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Users/gb/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/gb/.pyenv/versions/pyvo/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/tmpdsi1ni4h', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/ah_bootstrap.py", line 556, in _do_download
        dist.fetch_build_eggs(req)
      File "/Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/gb/.pyenv/versions/pyvo/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/gb/.pyenv/versions/pyvo/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/tmpdsi1ni4h', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/setup.py", line 8, in <module>
        import ah_bootstrap
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/ah_bootstrap.py", line 944, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/ah_bootstrap.py", line 263, in main
        bootstrapper.run()
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/ah_bootstrap.py", line 345, in run
        dist = method()
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/ah_bootstrap.py", line 413, in get_local_directory_dist
        upgrade = self._do_upgrade(dist)
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/ah_bootstrap.py", line 593, in _do_upgrade
        return self._do_download(version=upgrade.version)
      File "/private/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/pip-install-5crso78z/pyvo_0bf0886130244d5eb2f1535073b4fb08/ah_bootstrap.py", line 578, in _do_download
        raise Exception(msg.format(DIST_NAME, source, repr(e)))
    Exception: Error retrieving astropy-helpers from PyPI:
    DistutilsError("Command '['/Users/gb/.pyenv/versions/pyvo/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/x4/y38zs5fj4szf7xj3354kv74m0000gn/T/tmpdsi1ni4h', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.")
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9b/7f/f593e8ca1b2e24106165c6ecb47b4416afe346b5ff158f559cb3dd4e8d88/pyvo-1.1.tar.gz#sha256=e14f527ecbec48b71d57f48f301ec6a809f886096114529cf2d1fdcbaf6deb2b (from https://pypi.org/simple/pyvo/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyvo==1.1
ERROR: No matching distribution found for pyvo==1.1
```

**Comment by cbanek** [comment]
Hi there!  Sorry to hear you are having problems installing pyvo.  I use ubuntu 20.04 and just installed the deadsnakes ppa to go from 3.9.0 to 3.9.1 but I'm not sure I repro this.  Doing some quick googling suggests that maybe running pip install wheel might help?

https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

**Comment by barentsen** [comment]
I am no longer able to reproduce this issue myself right now.  It must have been a transient or local problem.  Apologies for opening a false alarm issue!

**Comment by cbanek** [comment]
No worries at all, this happens to me all the time!
