### ISSUE TITLE
Astropy helpers bootstrap fails for non-PyPI index URL

### ISSUE THREAD

**Issue by anuppari** [astropy/pyvo#264]
When a index-url is set in the [pip config file](https://pip.pypa.io/en/stable/user_guide/#config-file), pyvo installation fails due to the AH bootstrapper failing. It appears to be trying to get astropy-helpers from PyPI rather than the correct index.

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-piqa6yml/pyvo_c56edf72dabc4dc5874efa5e7ad525fc/setup.py", line 8, in <module>
        import ah_bootstrap
      File "/tmp/pip-install-piqa6yml/pyvo_c56edf72dabc4dc5874efa5e7ad525fc/ah_bootstrap.py", line 944, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "/tmp/pip-install-piqa6yml/pyvo_c56edf72dabc4dc5874efa5e7ad525fc/ah_bootstrap.py", line 263, in main
        bootstrapper.run()
      File "/tmp/pip-install-piqa6yml/pyvo_c56edf72dabc4dc5874efa5e7ad525fc/ah_bootstrap.py", line 345, in run
        dist = method()
      File "/tmp/pip-install-piqa6yml/pyvo_c56edf72dabc4dc5874efa5e7ad525fc/ah_bootstrap.py", line 413, in get_local_directory_dist
        upgrade = self._do_upgrade(dist)
      File "/tmp/pip-install-piqa6yml/pyvo_c56edf72dabc4dc5874efa5e7ad525fc/ah_bootstrap.py", line 593, in _do_upgrade
        return self._do_download(version=upgrade.version)
      File "/tmp/pip-install-piqa6yml/pyvo_c56edf72dabc4dc5874efa5e7ad525fc/ah_bootstrap.py", line 578, in _do_download
        raise Exception(msg.format(DIST_NAME, source, repr(e)))
    Exception: Error retrieving astropy-helpers from PyPI:
    DistutilsError("Command '['~/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpmwo52dca', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 2.")
```

It appears that the bootstrap script requires the index-url to be [set in the `setup.cfg`](https://github.com/astropy/pyvo/blob/dd3914e01333cb91681d118fdfc98f1bfc2a543d/ah_bootstrap.py#L76) or CLI, but this isn't possible when pyvo is installed as a transitive dependency.

**Comment by bsipocz** [comment]
Do install the package `wheel`, it should resolve this build issue.

Duplicate of #228

**Comment by anuppari** [comment]
Yep now that the wheels are on PyPI, this error no longer occurs during install. However, if installing without wheels and the ah bootstrap continues to be used, then I think this is still an issue.
