### ISSUE TITLE
BUG: pyvo 1.2.1 fails to pip install

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/pyvo#296]
reproducer
```
python3.8 -m venv .env
source .env/bin/activate
python -m pip install --upgrade pip
python -m pip install pyvo
```

<details> <summary> Traceback </summary>

```
Collecting pip==22.0.0
  Downloading pip-22.0-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 10.1 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-22.0

╭─   /tmp ································································································································  4s  .env  11:46:34
╰─❯ pip install pyvo
Collecting pyvo
  Using cached pyvo-1.2.1.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [6 lines of output]
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help

            error: invalid command 'bdist_wheel'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for astropy-helpers
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/private/tmp/.env/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/Users/robcleme/.pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/private/tmp/.env/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/tmpbufu5erj', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/ah_bootstrap.py", line 556, in _do_download
          dist.fetch_build_eggs(req)
        File "/private/tmp/.env/lib/python3.8/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/private/tmp/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/private/tmp/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/private/tmp/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/private/tmp/.env/lib/python3.8/site-packages/setuptools/dist.py", line 780, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/private/tmp/.env/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/private/tmp/.env/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/tmpbufu5erj', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/setup.py", line 8, in <module>
          import ah_bootstrap
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/ah_bootstrap.py", line 944, in <module>
          BOOTSTRAPPER = _Bootstrapper.main()
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/ah_bootstrap.py", line 263, in main
          bootstrapper.run()
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/ah_bootstrap.py", line 345, in run
          dist = method()
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/ah_bootstrap.py", line 413, in get_local_directory_dist
          upgrade = self._do_upgrade(dist)
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/ah_bootstrap.py", line 593, in _do_upgrade
          return self._do_download(version=upgrade.version)
        File "/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/pip-install-btaa6bpq/pyvo_1d837803895846eab0fe6311d1e1d6c8/ah_bootstrap.py", line 578, in _do_download
          raise Exception(msg.format(DIST_NAME, source, repr(e)))
      Exception: Error retrieving astropy-helpers from PyPI:
      DistutilsError("Command '['/private/tmp/.env/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/tmpbufu5erj', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.")
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0; however, version 22.0.2 is available.
You should consider upgrading via the '/private/tmp/.env/bin/python3.8 -m pip install --upgrade pip' command.
```

</details>

tested with pip 22.0.0 and 22.0.2 (current latest release)

**Comment by grburgess** [comment]
I think I found a way around this by using:

```
python3 -m pip install --upgrade pip wheel;
pip3 install cryptography pyOpenSSL pyvo pyRXP --upgrade;

```

It at least works in GitHub actions.

**Comment by neutrinoceros** [comment]
This is still happening with pyvo 1.2.1

**Comment by timothygebhard** [comment]
I'm running into the same issue on GitHub actions (with pip 22.0.3 and pyvo 1.2.1, for both Python 3.8 and 3.9): 

<details>
<summary>Traceback:</summary>

```
Collecting pyvo>=1.1
  Downloading pyvo-1.2.1.tar.gz (840 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.5/840.5 KB 93.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [181 lines of output]
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4rc1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4rc2 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4rc3 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.2 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.3 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.4 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.5 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.6 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.7 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-0.4.8 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0.1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0.2 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0.3 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0.4 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0.5 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0.6 is an invalid version and will not be supported in a future release
        warnings.warn(
      /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: helpers-1.0.7 is an invalid version and will not be supported in a future release
        warnings.warn(
      
      Traceback (most recent call last):
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/ah_bootstrap.py", line 556, in _do_download
          dist.fetch_build_eggs(req)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/setuptools/dist.py", line 821, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
          dist = best[req.key] = env.best_match(
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1062, in best_match
          return self.obtain(req, installer)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1074, in obtain
          return installer(requirement)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/setuptools/dist.py", line 892, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/opt/hostedtoolcache/Python/3.8.12/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplxe2quge', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/setup.py", line 8, in <module>
          import ah_bootstrap
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/ah_bootstrap.py", line 944, in <module>
          BOOTSTRAPPER = _Bootstrapper.main()
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/ah_bootstrap.py", line 263, in main
          bootstrapper.run()
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/ah_bootstrap.py", line 345, in run
          dist = method()
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/ah_bootstrap.py", line 413, in get_local_directory_dist
          upgrade = self._do_upgrade(dist)
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/ah_bootstrap.py", line 593, in _do_upgrade
          return self._do_download(version=upgrade.version)
        File "/tmp/pip-install-181nx8k6/pyvo_2821e3df40bb4d129daf138e036df706/ah_bootstrap.py", line 578, in _do_download
          raise Exception(msg.format(DIST_NAME, source, repr(e)))
      Exception: Error retrieving astropy-helpers from PyPI:
      DistutilsError("Command '['/opt/hostedtoolcache/Python/3.8.12/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplxe2quge', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==3.2.2']' returned non-zero exit status 1.")
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.
```

</details>

I'm actually not even using pyvo directly; it is just being installed as a dependency of astroquery.

Maybe @bsipocz has an idea for a fix / workaround? 🙂 

[Interestingly, a local installation on my Mac (macOS 10.15, Python 3.9.7) seems to go through without any problems?]

**Comment by bsipocz** [comment]
Unfortunately, there hasn't been a wheel uploaded for the latest release on pypi. It will need someone with upload rights to get that fixed, but I would expect it will be resolved in a few days.

In the meantime, if you pip install `wheel` it should fix the build error you see.

**Comment by neutrinoceros** [comment]
Oh that's why. I didn't think to check for that. Thanks !

**Comment by bsipocz** [comment]
Yeah, unfortunately, the tracelog is a bit cryptic for this to see the real issue straight away.

**Comment by timothygebhard** [comment]
> In the meantime, if you pip install wheel it should fix the build error you see.

I can confirm that this works! Awesome — thanks a lot! 🥳 

In case anybody else is encountering this problem with GitHub Actions: It's _not_ sufficient to just add `wheel` to your list of requirements; you want an extra step in your workflow to install `wheel` _before_ running whatever step that will try to install `pyvo`. Kind of obvious in hindsight, but I just thought I'd leave it here as a comment 🙂

**Comment by tomdonaldson** [comment]
I've uploaded the wheel to pypi.  Hopefully this resolves the issue.
```
git checkout v1.2.1
python setup.py build bdist_wheel
twine upload dist/* --verbose  --skip-existing
```

**Comment by neutrinoceros** [comment]
Confirmed, this resolved the issue on my end. Thank you very much !

**Comment by neutrinoceros** [comment]
no worries, this things happen :)
