### ISSUE TITLE
`AsyncTAPJob` raises exception when getting `phase` during connection problems or when job is removed

### ISSUE THREAD

**Issue by JannisNe** [astropy/pyvo#376]
My code [`timewise`](https://github.com/JannisNe/timewise) uses `AsynTAPJob.phase` to check if the job is done. If a timeout occurs while calling `AsynTAPJob._update()`, an `AttributeError` will be raised while trying to construct a `DALServiceError` through `DALServiceError.from_except()` (see the last couple of lines in the stack trace below). This is partly mentioned in #365. 
A solution could be to add a [`backoff`](https://pypi.org/project/backoff/) decorator to `AsynTAPJob._update()`

```
Traceback (most recent call last):
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, 
in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, 
in _make_request
    httplib_response = conn.getresponse()
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:
                                                                                                                             
Traceback (most recent call last):
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/requests/adapters.py", line 489, in se
nd
    resp = conn.urlopen(
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, 
in urlopen
    retries = retries.increment(
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in i
ncrement
    raise six.reraise(type(error), error, _stacktrace)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in
 reraise
    raise value
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, 
in urlopen
    httplib_response = self._make_request(
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, 
in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, 
in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='irsa.ipac.caltech.edu', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/pyvo/dal/tap.py", line 662, in _update
    response = self._session.get(self.url, stream=True, timeout=timeout)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/requests/sessions.py", line 600, in ge
t
    return self.request("GET", url, **kwargs)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/requests/sessions.py", line 587, in re
quest
    resp = self.send(prep, **send_kwargs)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/requests/sessions.py", line 701, in se
nd
    r = adapter.send(request, **kwargs)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/requests/adapters.py", line 578, in se
nd
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='irsa.ipac.caltech.edu', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/timewise/wise_bigdata_desy_cluster.py"
, line 296, in _tap_thread
    if self.tap_jobs[t_before][chunk].phase == "COMPLETED":
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/pyvo/dal/tap.py", line 700, in phase
    self._update()
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/pyvo/dal/tap.py", line 665, in _update
    raise DALServiceError.from_except(ex, self.url)
  File "/lustre/fs23/group/icecube/necker/anaconda3/envs/air_flares/lib/python3.10/site-packages/pyvo/dal/exceptions.py", line 187, in 
from_except
    content_type = response.headers.get('content-type', None)
AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by msdemlei** [comment]
On Thu, Oct 13, 2022 at 02:41:36AM -0700, Jannis Necker wrote:
> A solution could be to add a
> [`backoff`](https://pypi.org/project/backoff/) decorator to
> `AsynTAPJob._update()`

Hm... First, I'm not so wild about accepting a new dependency for
such a rather rare situation, in particular because if a site has
gone down, there's a good chance the job will be gone anyway once
it's back (although I acknowledge that there are many situations when
the backend has just chugged on).  Hiding such a failure, anyway,
needs to be done with care anyway, or we'll hide permanent failures
in hard-to-debug ways.

On the other hand, I give you that it would be nice to be a bit more
robust against an occasional fluke or lost packet.  I don't have a
proposal in that direction I'd be happy with, though.  What I think
I'd least dislike would be a new property, robust_phase or so that
would return None if no phase can be determined.

On the other hand, I think what we ought to do when we're
raising any sort of exception out of an async job is include the job
URL in the message and perhaps a hint they can perhaps resume the job
there.  This could be helpful when otherwise hours of CPU time on the
server might get lost because of a fluke and a missing URL.

**Comment by JannisNe** [comment]
Coming back to this I think there is also another bug in this. The Error that should be raised is a `DALServiceError`. But if the response is `None` we get the `AttributeError` from [L.187](https://github.com/astropy/pyvo/blob/2ada6363f2d873b104c53dc0c9f6e270688114c5/pyvo/dal/exceptions.py#L187) in `pyvo.dal.exceptions`. A solution would be to move [L. 187-189](https://github.com/astropy/pyvo/blob/2ada6363f2d873b104c53dc0c9f6e270688114c5/pyvo/dal/exceptions.py#L187-L189) up into the `if` clause in [L184](https://github.com/astropy/pyvo/blob/2ada6363f2d873b104c53dc0c9f6e270688114c5/pyvo/dal/exceptions.py#L184).
I can submit the corresponding PR if you think this is a good way of dealing with it, @msdemlei.

**Comment by msdemlei** [comment]
You mean: move into the try-except?  Yeah, that would definitely be an improvement, yes.

**Comment by msdemlei** [comment]
On Tue, Jan 03, 2023 at 04:52:04AM -0800, Jannis Necker wrote:
>             if response is not None:
>                 code = response.status_code
>                 content_type = response.headers.get('content-type', None)
>                 if content_type and 'text/plain' in content_type:
>                     message = '{} for {}'.format(response.text, URL)
>             else:
>                 message = str(exc)

Looks good to me, sure.  A PR to that effect would be most
appreciated - Thanks!
