### ISSUE TITLE
Query crashes

### ISSUE THREAD

**Issue by bhilbert4** [astropy/pyvo#437]
Our pyvo queries are suddenly crashing with a config error:

```
instrument = 'nircam'
proposal = '01981'
tap_service = vo.dal.TAPService("https://vao.stsci.edu/caomtap/tapservice.aspx")
tap_results = tap_service.search(f"select observationID from dbo.CaomObservation where collection='JWST' and maxLevel=2 and insName like '{instrument.lower()}%' and prpID='{int(proposal)}'")
prop_table = tap_results.to_table()
rootnames = prop_table['observationID'].data
```
Results in:
```
---------------------------------------------------------------------------
DALQueryError                             Traceback (most recent call last)
<ipython-input-4-c42c63db2a34> in <module>
      1 tap_service = vo.dal.TAPService("https://vao.stsci.edu/caomtap/tapservice.aspx")
----> 2 tap_results = tap_service.search(f"select observationID from dbo.CaomObservation where collection='JWST' and maxLevel=2 and insName like '{instrument.lower()}%' and prpID='{int(proposal)}'")
      3 prop_table = tap_results.to_table()
      4 rootnames = prop_table['observationID'].data

~/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/pyvo/dal/tap.py in run_sync(self, query, language, maxrec, uploads, **keywords)
    253         TAPResults
    254         """
--> 255         return self.create_query(
    256             query, language=language, maxrec=maxrec, uploads=uploads,
    257             **keywords).execute()

~/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/pyvo/dal/tap.py in execute(self)
   1074            for errors parsing the VOTable response
   1075         """
-> 1076         return TAPResults(self.execute_votable(), url=self.queryurl, session=self._session)
   1077 
   1078     def submit(self, post=False):

~/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/pyvo/dal/adhoc.py in __init__(self, votable, url, session)
    109 
    110     def __init__(self, votable, url=None, session=None):
--> 111         super().__init__(votable, url=url, session=session)
    112 
    113         self._adhocservices = list(

~/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/pyvo/dal/query.py in __init__(self, votable, url, session)
    317         self._status = self._findstatus(votable)
    318         if self._status[0].lower() not in ("ok", "overflow"):
--> 319             raise DALQueryError(self._status[1], self._status[0], url)
    320 
    321         if self._status[0].lower() == "overflow":

DALQueryError: General Error: Config for target service URL not found: https://vao.stsci.edu/caomtap/tapservice.aspxjava.lang.Exception: Config for target service URL not found: https://vao.stsci.edu/caomtap/tapservice.aspx
	at edu.stsci.adqltranslator.app.ServiceInfo.<init>(ServiceInfo.java:86)
	at edu.stsci.adqltranslator.app.runner.parseAndTranslate(runner.java:100)
	at edu.stsci.adqltranslator.app.runner.parseAndTranslate(runner.java:74)
	at edu.stsci.adqltranslator.app.DBTranslateServlet.handleRequest(DBTranslateServlet.java:116)
	at edu.stsci.adqltranslator.app.DBTranslateServlet.doPost(DBTranslateServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:352)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:171)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$Wrappin
```

**Comment by theresadower** [comment]
That is coming from the (my) microservice ADQL to MAST's DB dialect; possibly a version on one of the resolver servers isn't liking the update to https. I'll look into it ASAP.

**Comment by theresadower** [comment]
One of the resolver servers hadn't caught an update that we're moving to https; I've updated it and tested to each server directly. The issue should be resolved. Please comment here and/or ping me directly if it comes back!

**Comment by bhilbert4** [comment]
Queries are now working for me as well. Thanks for the quick fix!
