### ISSUE TITLE
import pyvo fails: ImportError: cannot import name 'wraps' from 'astropy.utils.decorators' 

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/pyvo#494]
Sorry if this is known issue

I am on a Mac running Ventura 13.6 (22G120)

Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:05:36)
[Clang 14.0.6 ] on darwin

>>> import astropy
>>> print(astropy.__version__)
5.2.2

>>> import pyvo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rgm/anaconda3/lib/python3.8/site-packages/pyvo/__init__.py", line 37, in <module>
    from . import registry
  File "/Users/rgm/anaconda3/lib/python3.8/site-packages/pyvo/registry/__init__.py", line 7, in <module>
    from . import regtap
  File "/Users/rgm/anaconda3/lib/python3.8/site-packages/pyvo/registry/regtap.py", line 19, in <module>
    from ..dal import scs, sia, ssa, sla, tap, query as dalq
  File "/Users/rgm/anaconda3/lib/python3.8/site-packages/pyvo/dal/__init__.py", line 2, in <module>
    from .sia import search as imagesearch
  File "/Users/rgm/anaconda3/lib/python3.8/site-packages/pyvo/dal/sia.py", line 39, in <module>
    from .query import DALResults, DALQuery, DALService, Record
  File "/Users/rgm/anaconda3/lib/python3.8/site-packages/pyvo/dal/query.py", line 47, in <module>
    from ..utils.decorators import stream_decode_content
  File "/Users/rgm/anaconda3/lib/python3.8/site-packages/pyvo/utils/decorators.py", line 4, in <module>
    from astropy.utils.decorators import wraps
ImportError: cannot import name 'wraps' from 'astropy.utils.decorators' (/Users/rgm/anaconda3/lib/python3.8/site-packages/astropy/utils/decorators.py)

**Comment by bsipocz** [comment]
@richardgmcmahon - I suspect you use a rather old pyvo, this should be fixed in versions >=v1.2.1

**Comment by richardgmcmahon** [comment]
thanks.

 pip install --upgrade pyvo
 
 ....
 
 Installing collected packages: pyvo
  Attempting uninstall: pyvo
    Found existing installation: pyvo 1.1
    Uninstalling pyvo-1.1:
      Successfully uninstalled pyvo-1.1
Successfully installed pyvo-1.4.2

>>> import pyvo
>>> print(pyvo.__version__)
1.4.2
